config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  delete "messages/:id" => "messages#destroy"
  get 'comments/index'
  delete 'messages' => 'messages#destroy'
  delete 'responses' => 'responses#destroy'
  get 'responses/create' => 'responses#create'
  get 'agrees' => 'agrees#show'
  get 'explanations' => 'explanations#index'
  get 'tips/lists' => 'tips#lists'
  get 'tips/questions' => 'tips#questions'
  get 'tips/hours' => 'tips#hours'
  get 'tips/levels' => 'tips#levels'
  get 'tips/commentnum' => 'tips#commentnum'
  get 'rooms/students' => 'rooms#students'
  get 'messages/students' => 'messages#students'
  get 'messages/list' => 'messages#list'
  get 'messages/levelup' => 'messages#levelup'
  get 'diaries/count_words' => 'diaries#count_words'
  get '/users/sign_out' => 'devise/sessions#destroy'

  root to: "rooms#index"
  resources :users, only: [:edit, :update] do
    resources :diaries, only: [:index, :new, :create,:destroy, :show]  end

  resources :rooms do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :tasks
  end

  resources :messages, only: [:index, :new, :create, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  resources :comments do
    resources :agrees, only: [:create, :destroy]
  end

  resources :comments do
    resources :responses, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :tips
  end

  resources :diaries do
    resources :replies, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :exams, only: [:new, :create, :destroy, :show]
  end
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    belongs_to :room
    has_one_attached :image
    has_many :comments

    validates :content, presence: true, unless: :was_attached?

    def was_attached?
        self.image.attached?
    end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :trackable, :recoverable, :rememberable, :validatable


  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :comments
  has_many :responses
  has_many :agrees, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :events
  
with_options presence: true do
  validates :email
  validates :name
  validates :genre
  validates :grade
  validates :class_number
  validates :student_number

end


  def already_agreed?(comment)
    self.agrees.exists?(comment_id: comment.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @comment = Comment.new
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user).order("created_at DESC")
    @users = @room.users.order("student_number ASC")
    @tasks = @room.tasks
  end
  
  def new
    @room = Room.find(params[:room_id])
    @comment = Comment.new
    @message = Message.new
  end
  
  def show
    @comment = Comment.new
    @message = Message.new
    @comments = @message.comments.includes(:user)
  end

  def students
    @users = User.all
  end

  def create
    @room = Room.find(params[:id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      render :index
    end
  end

  def destroy
    @room = Room.find(params[:room_id])
    @message = Message.find(params[:id])    
    if @message.destroy
      return redirect_to room_messages_path(@message.room)
    else
       render :new
    end
   end

  def list 
    @users = User.all.order("class_number ASC").order("student_number ASC")
    @ids = current_user.diary_ids

    # １学年用
    @users_num11 = User.all.where(grade:1, class_number: 1)
    @users_num12 = User.all.where(grade:1, class_number: 2)
    @users_num13 = User.all.where(grade:1, class_number: 3)
    @users_num14 = User.all.where(grade:1, class_number: 4)
    @users_num15 = User.all.where(grade:1, class_number: 5)
    @users_num16 = User.all.where(grade:1, class_number: 6)

    # 2学年用
    @users_num21 = User.all.where(grade:2, class_number: 1)
    @users_num22 = User.all.where(grade:2, class_number: 2)
    @users_num23 = User.all.where(grade:2, class_number: 3)
    @users_num24 = User.all.where(grade:2, class_number: 4)
    @users_num25 = User.all.where(grade:2, class_number: 5)
    @users_num26 = User.all.where(grade:2, class_number: 6)

    # 2学年用
    @users_num31 = User.all.where(grade:3, class_number: 1)
    @users_num32 = User.all.where(grade:3, class_number: 2)
    @users_num33 = User.all.where(grade:3, class_number: 3)
    @users_num34 = User.all.where(grade:3, class_number: 4)
    @users_num35 = User.all.where(grade:3, class_number: 5)
    @users_num36 = User.all.where(grade:3, class_number: 6)

  end

  def levelup
    @users = User.all
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
end

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <div class="room-wrapper">
        <%= link_to @room.name, root_path, class:"room-name3" %>

            <%if @room.tasks.present?%>
              <div><%=link_to "連絡",new_room_task_path(@room), class:"qs6 blue" %></div>
            <%else%>
              <div><%=link_to "連絡",new_room_task_path(@room), class:"qs6" %></div>
            <%end%>

    <%@tasks.each do |task|%>
        <%unless task.deadline.strftime('%m%d%H:%M').to_i < DateTime.current.strftime('%m%d%H:%M').to_i%>
    <%if task.deadline.strftime('%m%d').to_i <= DateTime.current.since(1.days).strftime('%m%d').to_i%> 
    <span class="envelop-red"><i class="far fa-envelope"></i></span>
    <%elsif task.deadline.strftime('%m%d').to_i > DateTime.current.since(1.days).strftime('%m%d').to_i%>
     <span class="envelop-blue"><i class="far fa-envelope"></i></span>
    <%end %> 
    <%end%>
    <%end%>
    </div>

    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <% if current_user.genre == "教員"%>
    <%=button_to "ルーム削除", room_path(@room), method: :delete %>
    <% end %>
    </div>
  </div>
</div>

<div class="messages">
  <div id="image-list"></div>
   <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: @message, class: 'form', local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="form-input2">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image,placeholder: "画像のURL" ,class: 'hidden' %>
    </label>
      <%= hidden_field_tag :id,@room.id %>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
  <%= image_tag @message.image, id: 'image' if @message.image.present? %> 
<% end %>

<script>
document.addEventListener('DOMContentLoaded', function(){
    const ImageList = document.getElementById('image-list');
  
    document.getElementById('message_image').addEventListener('change', function(e){
      const file = e.target.files[0];
      const blob = window.URL.createObjectURL(file);
      const imageElement = document.createElement('div');
      const blobImage = document.createElement('img');
      blobImage.setAttribute('src', blob);
      imageElement.appendChild(blobImage);
      ImageList.appendChild(imageElement);
    });
  });
</script>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <%=message.created_at.strftime('%m月%d日 %H:%M') if message.user.current_sign_in_at%>
    </div>
    <div class="message-date">
      【質問<%= message.comments.count %>個】
    </div>
    <div>
    <% if current_user.genre == "教員" %>
      <p>
        <%= button_to room_message_path(@room.id, message.id) ,method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
      <% elsif user_signed_in? && current_user.id == message.user_id %>
      <p>
        <%= button_to room_message_path(@room.id, message.id), method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
    <% end %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%=link_to message.content, new_message_comment_path(message) %>
    </div>
     <%= link_to  new_message_comment_path(message) do %>
     <%=image_tag message.image.variant(resize: '400x400'), class: 'message-image' if message.image.attached? %>
     <%end%>

  </div>
</div>

app/views/messages/_one.html.erb
<div class="wrapper1">
<div class="grade" id="first">１年</div>
<div class="class-number" id="oneone"><span>1組</span><span>（<%=@users_num11.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-1">
        <% if user.grade == 1 && user.class_number == 1%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <span class="user-name"><%= user.name%></span>
        <% end %>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <% end %>
    </div>
    <% end %>
</div>

<div class="class-number" id="onetwo"><span>２組</span><span>（<%=@users_num12.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-2">
        <% if user.grade == 1 && user.class_number == 2%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <%= user.name%>
        <%end%>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <% end %>
    </div>
    <% end %>
</div>

<div class="class-number" id="onethree"><span>３組</span><span>（<%=@users_num13.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-3">
        <% if user.grade == 1 && user.class_number == 3%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <%= user.name%>
        <%end%>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <%end%>
    </div>
    <%end%>
</div>


<div class="class-number" id="onefour"><span>４組</span><span>（<%=@users_num14.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-4">
        <% if user.grade == 1 && user.class_number == 4%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <%= user.name%>
        <%end%>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <% end %>
    </div>
        <%end%>
</div>

<div class="class-number" id="onefive"><span>５組</span><span>（<%=@users_num15.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-5">
        <% if user.grade == 1 && user.class_number == 5%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <%= user.name%>
        <%end%>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <% end %>
    </div>
        <%end%>
</div>

<div class="class-number" id="onesix"><span>６組</span><span>（<%=@users_num16.count%>名）</span></div>
<div class="lists">
<% @users.each do |user|%>
    <div class="hidden wid list1-6">
        <% if user.grade == 1 && user.class_number == 6%>
        <%= user.student_number%>番
        <%=link_to new_user_diary_path(user) do %>
        <%= user.name%>
        <%end%>
        <% @login = user.current_sign_in_at.strftime('%m月%d日 %H:%M') if user.current_sign_in_at%>
            <%if @login > Date.current.ago(6.days || 7.days || 8.days)%>
            <span class="login-day">５日間以上</span>
            <%elsif @login > Date.current.ago(5.days)%>
            <span class="login-day">５日前</span>
            <%elsif @login > Date.current.ago(4.days)%>
            <span class="login-day">４日前</span>
            <%elsif @login > Date.current.ago(3.days)%>
            <span class="login-day">３日前</span>
            <%elsif @login > Date.current.ago(2.days)%>
            <span class="login-day">２日前</span>
            <%elsif @login > Date.current.ago(1.days)%>
            <span class="login-day">１日前</span>
            <%elsif @login = Date.today%>
            <span class="login-day-today"></span>
            <%end %>
        <% end %>
    </div>
    <%end%>
</div>
</div>

<script>
    let one11 = document.getElementById('oneone');
    let members11 = document.querySelectorAll('.list1-1');

        one11.addEventListener('click', function(){
        for(const member11 of members11) {
        if (member11.getAttribute('style') == 'display:block;') {
            member11.removeAttribute('style','display:block;')
        } else {
            member11.setAttribute('style','display:block;')
        }
     }
    })

    let one12 = document.getElementById('onetwo');
    let members12 = document.querySelectorAll('.list1-2');

        one12.addEventListener('click', function(){
        for(const member12 of members12) {
        if (member12.getAttribute('style') == 'display:block;') {
            member12.removeAttribute('style','display:block;')
        } else {
            member12.setAttribute('style','display:block;')
        }
     }
    })

    let one13 = document.getElementById('onethree');
    let members13 = document.querySelectorAll('.list1-3');

        one13.addEventListener('click', function(){
        for(const member13 of members13) {
        if (member13.getAttribute('style') == 'display:block;') {
            member13.removeAttribute('style','display:block;')
        } else {
            member13.setAttribute('style','display:block;')
        }
     }
    })

    let one14 = document.getElementById('onefour');
    let members14 = document.querySelectorAll('.list1-4');

        one14.addEventListener('click', function(){
        for(const member14 of members14) {
        if (member14.getAttribute('style') == 'display:block;') {
            member14.removeAttribute('style','display:block;')
        } else {
            member14.setAttribute('style','display:block;')
        }
     }
    })

    let one15 = document.getElementById('onefive');
    let members15 = document.querySelectorAll('.list1-5');

        one15.addEventListener('click', function(){
        for(const member15 of members15) {
        if (member15.getAttribute('style') == 'display:block;') {
            member15.removeAttribute('style','display:block;')
        } else {
            member15.setAttribute('style','display:block;')
        }
     }
    })

    let one16 = document.getElementById('onesix');
    let members16 = document.querySelectorAll('.list1-6');

        one16.addEventListener('click', function(){
        for(const member16 of members16) {
        if (member16.getAttribute('style') == 'display:block;') {
            member16.removeAttribute('style','display:block;')
        } else {
            member16.setAttribute('style','display:block;')
        }
     }
    })



</script>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
  <% if current_user.genre == "生徒" %>
    <%= link_to current_user.name+"（生徒）", edit_user_path(current_user) %>
   <%= render "layouts/level" %>
  <% else %>
    <%= link_to current_user.name+"（教員）", edit_user_path(current_user) %>
  <% end %>
  <div class="white"><%=current_user.current_sign_in_at.strftime('%m/%d %H:%M') if current_user.current_sign_in_at%></div>
  </div>
  <% if current_user.genre == "生徒" %>
  <%=link_to '記録',new_user_diary_path(current_user.id),class:"diary"%>
  <% end %>
  <div class="create-room">
  <% if current_user.genre == "教員" %>
    <%=link_to "ルーム作成", new_room_path %>
  <%end%>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
         <%=link_to room.name, room_messages_path(room) %>
         <%=link_to room_path(room) do %> 
         <p class="room-num">(<%= room.users.count-1 %>名)</p>
         <% end %>
      </div>
    </div>
    <%end%>
  <div class="room-members">  

  </div>
</div>

app/views/messages/_side_bar2.html.erb
<div class="side-bar-header">
  <div class="header-name">
  <% if current_user.genre == "生徒" %>
    <%= link_to current_user.name+"（生徒）", edit_user_path(current_user) %>
    <%= render "layouts/level" %>
  <% else %>
    <%= link_to current_user.name+"（教員）", edit_user_path(current_user) %>
  <% end %>
  <div class="white"><%=current_user.current_sign_in_at.strftime('%m/%d %H:%M') if current_user.current_sign_in_at%></div>
  </div>
  <% if current_user.genre == "生徒" %>
  <%=link_to '記録',new_user_diary_path(current_user.id),class:"diary"%>
  <% end %>
  <div class="create-room">
  <% if current_user.genre == "教員" %>
    <%=link_to "ルーム作成", new_room_path %>
  <%end%>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
         <%=link_to room.name, room_messages_path(room) %>
         <%=link_to room_path(room) do %> 
           <p class="room-num">(<%= room.users.count-1%>名)</p>
         <% end %>
      </div>
    </div>
    <%end%>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/messages/levelup.html.erb
   <%level_count = current_user.diary_ids.length + current_user.comment_ids.length*1.2 + current_user.response_ids.length*1.5%>
   
   <div class="current-info">
      <div><%=current_user.name%>さん(<%=level_count.round%>ポイント)</div>
      <div><%=render "layouts/level2" %></div>
      <%if level_count < 15 %>
      <div>次のレベルまで<%= 15 - level_count.to_i%>ポイント</div>
      <%end%>
   </div>

  <ul class="post-sums">
    <%if current_user.diary_ids.count <= level_count/3 %>
      <li>学習の記録<span><%= current_user.diary_ids.count%></span>個　少ない</li>
    <%elsif current_user.diary_ids.count > level_count/3%>
      <li>学習の記録<span><%= current_user.diary_ids.count%></span>個　<span class="good2">👍</span></li>
    <%else%>
      <li>学習の記録<span><%= current_user.diary_ids.count%></span>個</li>
    <%end%>

    <%if current_user.comment_ids.count <= level_count/3 %>
      <li>学習の記録<span><%= current_user.comment_ids.count%></span>個　少ない</li>
    <%elsif current_user.comment_ids.count > level_count/3%>
      <li>学習の記録<span><%= current_user.diary_ids.count%></span>個　<span class="good2">👍</span></li>
    <%else%>
      <li>学習の記録<span><%= current_user.comment_ids.count%></span>個</li>
    <%end%>

    <%if current_user.response_ids.count <= level_count/3 %>
      <li>学習の記録<span><%= current_user.response_ids.count%></span>個　少ない</li>
    <%elsif current_user.response_ids.count > level_count/3%>
      <li>学習の記録<span><%= current_user.diary_ids.count%></span>個　<span class="good2">👍</span></li>
    <%else%>
      <li>学習の記録<span><%= current_user.response_ids.count%></span>個</li>
    <%end%>
  <ul>

app/views/messages/list.html.erb
<div class="main-wrapper">
<%= render "one" %>
<%= render "two" %>
<%= render "three" %>
</div>

app/views/messages/students.html.erb
<%@users.each do |user| %>
<%if user.genre == '生徒'%>
 <div>
 <%=user.name%>
 <%=user.diary_ids.length + user.comment_ids.length + user.response_ids.length%>
 <% end %>
 <% end %>
 </div>