config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  delete "messages/:id" => "messages#destroy"
  get 'comments/index'
  delete 'messages' => 'messages#destroy'
  delete 'responses' => 'responses#destroy'
  get 'responses/create' => 'responses#create'
  get 'agrees' => 'agrees#show'
  get 'explanations' => 'explanations#index'
  get 'tips/lists' => 'tips#lists'
  get 'tips/questions' => 'tips#questions'
  get 'tips/hours' => 'tips#hours'
  get 'tips/levels' => 'tips#levels'
  get 'tips/commentnum' => 'tips#commentnum'
  get 'rooms/students' => 'rooms#students'
  get 'messages/students' => 'messages#students'
  get 'messages/list' => 'messages#list'
  get 'messages/levelup' => 'messages#levelup'
  get 'diaries/count_words' => 'diaries#count_words'
  get '/users/sign_out' => 'devise/sessions#destroy'

  root to: "rooms#index"
  resources :users, only: [:edit, :update] do
    resources :diaries, only: [:index, :new, :create,:destroy, :show]  end

  resources :rooms do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :tasks
  end

  resources :messages, only: [:index, :new, :create, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  resources :comments do
    resources :agrees, only: [:create, :destroy]
  end

  resources :comments do
    resources :responses, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :tips
  end

  resources :diaries do
    resources :replies, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :exams, only: [:new, :create, :destroy, :show]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :message
    belongs_to :user
    has_many :agrees, dependent: :destroy
    has_many :responses, dependent: :destroy
    has_many :agreed_users, through: :agrees, source: :user

    validates :text, presence: true, length: {maximum: 75 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
  def index    
    @messages = Message.all
    @room = Room.all
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.find(params[:message_id])
    @comments = @message.comments.order("created_at DESC")
    @comment = Comment.new
    @room = Room.all
  end

  def create
     @message = Message.find(params[:message_id])
     @comment = @message.comments.new(comment_params)
    if @comment.save
      redirect_to new_message_comment_path(@message)
    else
      @message = Message.find(params[:message_id])
      @comments = @message.comments.order("created_at DESC")
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @message = @comment.message
    if @comment.destroy
       redirect_to new_message_comment_path(@message)
    else
       @comments = @message.comments.order("created_at DESC")
       render :new
    end       
  end
    
      private
      def comment_params
        params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
      end
end

app/views/comments/new.html.erb
<div class="comment">
      <div class="comment-box">
      <%= form_with model: @comment,url:message_comments_path(@message),local: true do |f| %>
      <%= render 'layouts/error_messages2', model: f.object %>
        <%= f.text_area :text, placeholder: "質問する", class: "comment-text", id:"input" %>
        <%= hidden_field_tag :message_id,@message.id %>
      <p><span id="inputCounter">0</span></p>
      <p class="comment-warn">
        <p>他の生徒の質問で回答できる場合には積極的に回答してください！</p>
      </p>
      <br>
      <%= f.submit "質問する",class: "comment-btn"%>
      <div class="back-to-top2"><%=link_to '戻る', room_messages_path(@message.room) %></div>
     <% end %>
  </div>

<div class="comment-box2">
      <h4 class="comment-list">＜質問一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
        <div class="comment-content">
         <% if comment.user.genre == "教員" || comment.user.id == current_user.id %>
          <p>
            <div><%= link_to comment.user.name, new_user_diary_path(comment.user), class: "comment-nickname" %></div>
          </p>
         <% elsif current_user.genre == "教員" %> 
          <p>
            <div><%= link_to comment.user.name, new_user_diary_path(comment.user), class: "comment-nickname" %></div>
          </p>
          <% elsif current_user.genre == "生徒" %>
          <div class= "comment-nickname">匿名</div>
          <% end %>
          <div class="comment-texts">
            <%=link_to comment.text, new_comment_response_path(comment) %>
          </div>
          <div class="favorite-btn">
             <% if user_signed_in? && current_user.already_agreed?(comment) %>
              <%= button_to comment_agree_path(comment, comment.agrees), method: :delete do %>
              <div class="agree-btn-color">共感</div>
             <% end %>
             <% elsif user_signed_in? && current_user.id == comment.user_id%>
              <div class="agree-btn">共感</div>
             <% else %>
            <%= button_to comment_agrees_path(comment), method: :post do %>
             <div class="agree-btn">共感</div>
             <% end %>
             <% end %>
            <div class="agree-count"><%= comment.agrees.count%>人</div>
          </div>
          <div class="comment-time">
            <div class="time"><%= comment.created_at.to_s(:datetime_jp) %></div>
            <div class="time"><%= comment.created_at.to_s(:datetime_jp2) %></div>
          </div>
           <% if current_user.genre == "教員" %>
          <p>
            <%= button_to message_comment_path(@message.id, comment.id), method: :delete, class: "delete-button" do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </p>
          <% elsif user_signed_in? && current_user.id == comment.user_id %>
          <p>
            <%= button_to message_comment_path(@message.id, comment.id), method: :delete, class: "delete-button" do %>
            <i class="fas fa-trash"></i>
            <% end %>
          </p>
          <% end %>
          <p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <script>
    var input = document.getElementById("input");
    var span = document.getElementById("inputCounter");
    input.addEventListener("keyup", function(){
      if (input.value.length > 75) {
        span.textContent = "投稿できません"
        span.style.color = 'red';
      }else{
        span.textContent = input.value.length;
      }   
    });
  </script>