config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  delete "messages/:id" => "messages#destroy"
  get 'comments/index'
  delete 'messages' => 'messages#destroy'
  delete 'responses' => 'responses#destroy'
  get 'responses/create' => 'responses#create'
  get 'agrees' => 'agrees#show'
  get 'explanations' => 'explanations#index'
  get 'tips/lists' => 'tips#lists'
  get 'tips/questions' => 'tips#questions'
  get 'tips/hours' => 'tips#hours'
  get 'tips/levels' => 'tips#levels'
  get 'tips/commentnum' => 'tips#commentnum'
  get 'rooms/students' => 'rooms#students'
  get 'messages/students' => 'messages#students'
  get 'messages/list' => 'messages#list'
  get 'messages/levelup' => 'messages#levelup'
  get 'diaries/count_words' => 'diaries#count_words'
  get '/users/sign_out' => 'devise/sessions#destroy'

  root to: "rooms#index"
  resources :users, only: [:edit, :update] do
    resources :diaries, only: [:index, :new, :create,:destroy, :show]  end

  resources :rooms do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :tasks
  end

  resources :messages, only: [:index, :new, :create, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  resources :comments do
    resources :agrees, only: [:create, :destroy]
  end

  resources :comments do
    resources :responses, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :tips
  end

  resources :diaries do
    resources :replies, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :exams, only: [:new, :create, :destroy, :show]
  end
end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user
    has_one :reply

    with_options presence: true do
    validates :writing, length: {maximum: 200 }
    validates :title
    validates :study_content
    validates :study_time
    end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :trackable, :recoverable, :rememberable, :validatable


  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :comments
  has_many :responses
  has_many :agrees, dependent: :destroy
  has_many :diaries, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :exams, dependent: :destroy
  has_many :events
  
with_options presence: true do
  validates :email
  validates :name
  validates :genre
  validates :grade
  validates :class_number
  validates :student_number

end


  def already_agreed?(comment)
    self.agrees.exists?(comment_id: comment.id)
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

    def new
        @diary = Diary.new
        @user = User.find(params[:user_id])
        @users = User.all
        @diaries = @user.diaries.order("created_at DESC")
        @vocabulary = @diaries.where(study_content: "単語")
        @grammar = @diaries.where(study_content: "文法")
        @speaking = @diaries.where(study_content: "スピーキング")
        @listening = @diaries.where(study_content: "リスニング")
        @writing = @diaries.where(study_content: "ライティング")
        @reading = @diaries.where(study_content: "リーディング")
    end

    def create
        @diary = Diary.new(diary_params)
        if @diary.save
          redirect_to new_user_diary_path(current_user.id)
        else
          @user = User.find(params[:user_id])
          @diaries = @user.diaries.order("created_at DESC")
          render :new
        end
    end

    def destroy
        @diary = Diary.find(params[:id])
        @user = @diary.user
        if @diary.destroy
            redirect_to new_user_diary_path(@user)
        else
            redirect_to root_path
        end
    end

    def show
        @diary = Diary.find(params[:id])
        @user = @diary.user
        @diaries = @user.diaries
        @bar_chart = @diaries
        @vocabulary = @diaries.where(study_content: "単語")
        @grammar = @diaries.where(study_content: "文法")
        @speaking = @diaries.where(study_content: "スピーキング")
        @listening = @diaries.where(study_content: "リスニング")
        @writing = @diaries.where(study_content: "ライティング")
        @reading = @diaries.where(study_content: "リーディング")
    end

    private

    def diary_params
        params.require(:diary).permit(:writing, :title, :study_content, :study_time, :user_id).merge(user_id: current_user.id)
    end
end

app/views/diaries/_if.html.erb
<%@array_word = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "単語"%>
    <%@sum_word = diary.study_time%>
    <%@array_word << @sum_word%>
<%else%>
    <%@sum_word = 0%>
    <%@array_word << @sum_word%>
<%end%>
<%end%>



<%@array_grammar = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "文法"%>
    <%@sum_grammar = diary.study_time%>
    <%@array_grammar << @sum_grammar%>
<%else%>
    <%@sum_grammar = 0%>
    <%@array_grammar << @sum_grammar%>
<%end%>
<%end%>


<%@array_speaking = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "スピーキング"%>
    <%@sum_speaking = diary.study_time%>
    <%@array_speaking << @sum_speaking%>
<%else%>
    <%@sum_speaking = 0%>
    <%@array_speaking << @sum_speaking%>
<%end%>
<%end%>

<%@array_writing = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "ライティング"%>
    <%@sum_writing = diary.study_time%>
    <%@array_writing << @sum_writing%>
<%else%>
    <%@sum_writing = 0%>
    <%@array_writing << @sum_writing%>
<%end%>
<%end%>


<%@array_listening = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リスニング"%>
    <%@sum_listening = diary.study_time%>
    <%@array_listening << @sum_listening%>
<%else%>
    <%@sum_listening = 0%>
    <%@array_listening << @sum_listening%>
<%end%>
<%end%>



<%@array_reading = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リーディング"%>
    <%@sum_reading = diary.study_time%>
    <%@array_reading << @sum_reading%>
<%else%>
    <%@sum_reading = 0%>
    <%@array_reading << @sum_reading%>
<%end%>
<%end%>

app/views/diaries/_main.html.erb
<%= render "if" %>
<div class="chat-header2">
<div class="diary-title">学習<span class="small-no">の</span>記録</div>
  <div class="left-header">
    <div class="header-title">
    </div>
  </div>

  <div class="right-header">
    <div class="header-button">
    </div>
  </div>
</div>
<div class="messages1">
<div class="study-hour">

<div class="left-time-wrapper">
<%# 残り時間（分表示） %>

  <b>
  <div class="left-time">

    <%@sum = 120000 - (@array_word.sum + @array_reading.sum + @array_speaking.sum + @array_grammar.sum + @array_listening.sum + @array_writing.sum)%>
    <%if @sum >= 0%>
    <div class="left2"><%=120000 - (@array_word.sum + @array_reading.sum + @array_speaking.sum + @array_grammar.sum + @array_listening.sum + @array_writing.sum)%></div>
    <%else%>
    0
    <%end%>
    <p class="mins">mins</p>
  </div>
  </b>

<%# 残り時間（時間表示） %>
  <b class="mg">
  <div class="left-time">
    <p class="left"></p>

    <%if @sum >= 0%>
    <div class="left3"><%=@sum / 60 %></div>
    <%else%>
    0
    <%end%>
    <p class="mins">hours</p>
  </div>
  </b>
  
<%# 残り時間（％表示） %>
  </b>
  <b>
  <div class="left-time">
    <span class="left"></span>
    <%@percentage = (@array_word.sum + @array_reading.sum + @array_speaking.sum + @array_grammar.sum + @array_listening.sum + @array_writing.sum).to_f * 100 / 120000 %>
    <div class="left3"><%= @percentage.round(2) %></div>
    <p class="percent">％</p>
  </div>
  </b>
</div>

</div>

<%# -----------------学習時間合計値（開始）----------------- %>
<%@array_word = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "単語"%>
    <%@sum_word = diary.study_time%>
    <%@array_word << @sum_word%>
<%else%>
    <%@sum_word = 0%>
    <%@array_word << @sum_word%>
<%end%>
<%end%>


<%@array_grammar = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "文法"%>
    <%@sum_grammar = diary.study_time%>
    <%@array_grammar << @sum_grammar%>
<%else%>
    <%@sum_grammar = 0%>
    <%@array_grammar << @sum_grammar%>
<%end%>
<%end%>


<%@array_speaking = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "スピーキング"%>
    <%@sum_speaking = diary.study_time%>
    <%@array_speaking << @sum_speaking%>
<%else%>
    <%@sum_speaking = 0%>
    <%@array_speaking << @sum_speaking%>
<%end%>
<%end%>


<%@array_writing = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "ライティング"%>
    <%@sum_writing = diary.study_time%>
    <%@array_writing << @sum_writing%>
<%else%>
    <%@sum_writing = 0%>
    <%@array_writing << @sum_writing%>
<%end%>
<%end%>


<%@array_listening = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リスニング"%>
    <%@sum_listening = diary.study_time%>
    <%@array_listening << @sum_listening%>
<%else%>
    <%@sum_listening = 0%>
    <%@array_listening << @sum_listening%>
<%end%>
<%end%>


<%@array_reading = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リーディング"%>
    <%@sum_reading = diary.study_time%>
    <%@array_reading << @sum_reading%>
<%else%>
    <%@sum_reading = 0%>
    <%@array_reading << @sum_reading%>
<%end%>
<%end%>

<%# -----------------学習時間合計値（終了）----------------- %>

<% total = @array_word.sum + @array_reading.sum + @array_speaking.sum + @array_grammar.sum + @array_listening.sum + @array_writing.sum%>
<%if total > 31000%>
<i></i>
<%elsif total > 30000%>
<i class="fas fa-running d100"></i>
<%elsif total > 28500%>
<i class="fas fa-running d95"></i>
<%elsif total > 27000%>
<i class="fas fa-running d90"></i>
<%elsif total > 25500%>
<i class="fas fa-running d85"></i>
<%elsif total > 24000%>
<i class="fas fa-running d80"></i>
<%elsif total > 22500%>
<i class="fas fa-running d75"></i>
<%elsif total > 21000%>
<i class="fas fa-running d70"></i>
<%elsif total > 19500%>
<i class="fas fa-running d65"></i>
<%elsif total > 18000%>
<i class="fas fa-running d60"></i>
<%elsif total > 16500%>
<i class="fas fa-running d55"></i>
<%elsif total > 15000%>
<i class="fas fa-running d50"></i>
<%elsif total > 13500%>
<i class="fas fa-running d45"></i>
<%elsif total > 12000%>
<i class="fas fa-running d40"></i>
<%elsif total > 10500%>
<i class="fas fa-running d35"></i>
<%elsif total > 9000%>
<i class="fas fa-running d30"></i>
<%elsif total > 7500%>
<i class="fas fa-running d25"></i>
<%elsif total > 6000%>
<i class="fas fa-running d20"></i>
<%elsif total > 4500%>
<i class="fas fa-running d15"></i>
<%elsif total > 3000%>
<i class="fas fa-running d10"></i>
<%elsif total > 1500%>
<i class="fas fa-running d5"></i>
<%elsif total >= 0%>
<i class="fas fa-running d0"></i>
<%end%>


  <div class="roads">
    <div class="start">start</div>
    <div class="road"></div>
    <%# 10個目 3000分 %>
    <div class="road">100h</div>
    <%# 20個目 6000分 %>
    <div class="road"></div>
    <%# 30個目 9000分 %>
    <div class="road">200h</div>
    <%# 40個目 12,000分 %>
    <div class="road"></div>
    <%# 50個目 15,000分 %>
    <div class="road">300h</div>
    <%# 60個目 18,000分 %>
    <div class="road"></div>
    <%# 70個目 21,000分 %>
    <div class="road">400h</div>
    <%# 80個目 24,000分 %>
    <div class="road"></div>
    <%# 90個目 27,000分 %>
    <div class="road">500h</div>
    <%# 100個目 30,000分 %>
  </div>

<%if total > 61000%>
<i></i>
<%elsif total > 60000%>
<i class="fas fa-running d200"></i>
<%elsif total > 58500%>
<i class="fas fa-running d195"></i>
<%elsif total > 57000%>
<i class="fas fa-running d190"></i>
<%elsif total > 55500%>
<i class="fas fa-running d185"></i>
<%elsif total > 54000%>
<i class="fas fa-running d180"></i>
<%elsif total > 52500%>
<i class="fas fa-running d175"></i>
<%elsif total > 51000%>
<i class="fas fa-running d170"></i>
<%elsif total > 49500%>
<i class="fas fa-running d165"></i>
<%elsif total > 48000%>
<i class="fas fa-running d160"></i>
<%elsif total > 46500%>
<i class="fas fa-running d155"></i>
<%elsif total > 45000%>
<i class="fas fa-running d150"></i>
<%elsif total > 43500%>
<i class="fas fa-running d145"></i>
<%elsif total > 42000%>
<i class="fas fa-running d140"></i>
<%elsif total > 40500%>
<i class="fas fa-running d135"></i>
<%elsif total > 39000%>
<i class="fas fa-running d130"></i>
<%elsif total > 37500%>
<i class="fas fa-running d125"></i>
<%elsif total > 36000%>
<i class="fas fa-running d120"></i>
<%elsif total > 34500%>
<i class="fas fa-running d115"></i>
<%elsif total > 33000%>
<i class="fas fa-running d110"></i>
<%elsif total > 31500%>
<i class="fas fa-running d105"></i>
<%elsif total > 31000%>
<i class="fas fa-running d00"></i>
<%end%>

  <div class="roads">
    <div class="road"></div>
    <div class="road"></div>
    <%# 10個目 3000分 %>
    <div class="road">600h</div>
    <%# 20個目 6000分 %>
    <div class="road"></div>
    <%# 30個目 9000分 %>
    <div class="road">700h</div>
    <%# 40個目 12,000分 %>
    <div class="road"></div>
    <%# 50個目 15,000分 %>
    <div class="road">800h</div>
    <%# 60個目 18,000分 %>
    <div class="road"></div>
    <%# 70個目 21,000分 %>
    <div class="road">900h</div>
    <%# 80個目 24,000分 %>
    <div class="road"></div>
    <%# 90個目 27,000分 %>
    <div class="road">1,000h</div>
    <%# 100個目 30,000分 %>
  </div>


<%if total > 91000%>
<i></i>
<%elsif total > 90000%>
<i class="fas fa-running d300"></i>
<%elsif total > 88500%>
<i class="fas fa-running d295"></i>
<%elsif total > 87000%>
<i class="fas fa-running d290"></i>
<%elsif total > 85500%>
<i class="fas fa-running d285"></i>
<%elsif total > 84000%>
<i class="fas fa-running d280"></i>
<%elsif total > 82500%>
<i class="fas fa-running d275"></i>
<%elsif total > 81000%>
<i class="fas fa-running d270"></i>
<%elsif total > 79500%>
<i class="fas fa-running d265"></i>
<%elsif total > 78000%>
<i class="fas fa-running d260"></i>
<%elsif total > 76500%>
<i class="fas fa-running d255"></i>
<%elsif total > 75000%>
<i class="fas fa-running d250"></i>
<%elsif total > 73500%>
<i class="fas fa-running d245"></i>
<%elsif total > 72000%>
<i class="fas fa-running d240"></i>
<%elsif total > 70500%>
<i class="fas fa-running d235"></i>
<%elsif total > 69000%>
<i class="fas fa-running d230"></i>
<%elsif total > 67500%>
<i class="fas fa-running d225"></i>
<%elsif total > 66000%>
<i class="fas fa-running d220"></i>
<%elsif total > 64500%>
<i class="fas fa-running d215"></i>
<%elsif total > 63000%>
<i class="fas fa-running d210"></i>
<%elsif total > 61500%>
<i class="fas fa-running d205"></i>
<%elsif total > 61000%>
<i class="fas fa-running d00"></i>
<%end%>


  <div class="roads">
    <div class="road"></div>
    <div class="road"></div>
    <%# 10個目 3000分 %>
    <div class="road">1,100h</div>
    <%# 20個目 6000分 %>
    <div class="road"></div>
    <%# 30個目 9000分 %>
    <div class="road">1,200h</div>
    <%# 40個目 12,000分 %>
    <div class="road"></div>
    <%# 50個目 15,000分 %>
    <div class="road">1,300h</div>
    <%# 60個目 18,000分 %>
    <div class="road"></div>
    <%# 70個目 21,000分 %>
    <div class="road">1,400h</div>
    <%# 80個目 24,000分 %>
    <div class="road"></div>
    <%# 90個目 27,000分 %>
    <div class="road">1,500h</div>
    <%# 100個目 30,000分 %>
  </div>

<%if total > 120000%>
<i class="fas fa-running d400"></i>
<%elsif total > 118500%>
<i class="fas fa-running d395"></i>
<%elsif total > 117000%>
<i class="fas fa-running d390"></i>
<%elsif total > 115500%>
<i class="fas fa-running d385"></i>
<%elsif total > 114000%>
<i class="fas fa-running d380"></i>
<%elsif total > 112500%>
<i class="fas fa-running d375"></i>
<%elsif total > 111000%>
<i class="fas fa-running d370"></i>
<%elsif total > 109500%>
<i class="fas fa-running d365"></i>
<%elsif total > 108000%>
<i class="fas fa-running d360"></i>
<%elsif total > 106500%>
<i class="fas fa-running d355"></i>
<%elsif total > 105000%>
<i class="fas fa-running d350"></i>
<%elsif total > 103500%>
<i class="fas fa-running d345"></i>
<%elsif total > 102000%>
<i class="fas fa-running d340"></i>
<%elsif total > 100500%>
<i class="fas fa-running d335"></i>
<%elsif total > 99000%>
<i class="fas fa-running d330"></i>
<%elsif total > 97500%>
<i class="fas fa-running d325"></i>
<%elsif total > 96000%>
<i class="fas fa-running d320"></i>
<%elsif total > 94500%>
<i class="fas fa-running d315"></i>
<%elsif total > 93000%>
<i class="fas fa-running d310"></i>
<%elsif total > 91500%>
<i class="fas fa-running d305"></i>
<%elsif total > 91000%>
<i class="fas fa-running d00"></i>
<%end%>

  <div class="roads">
    <div class="road"></div>
    <div class="road"></div>
    <%# 10個目 3000分 %>
    <div class="road">1,600h</div>
    <%# 20個目 6000分 %>
    <div class="road"></div>
    <%# 30個目 9000分 %>
    <div class="road">1,700h</div>
    <%# 40個目 12,000分 %>
    <div class="road"></div>
    <%# 50個目 15,000分 %>
    <div class="road">18,00h</div>
    <%# 60個目 18,000分 %>
    <div class="road"></div>
    <%# 70個目 21,000分 %>
    <div class="road">1,900h</div>
    <%# 80個目 24,000分 %>
    <div class="road"></div>
    <%# 90個目 27,000分 %>
    <div class="goal">goal</div>
    <%# 100個目 30,000分 %>
  </div>



   <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@user,@diary],class: 'form2', local: true do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="form-input">
      <div class="study-title"><%= f.text_area :title,class: 'form-message4', placeholder: 'title' %></div>
      <div class="studies">
        <div class="study-hour"><%= f.select :study_content, [["content",nil],["vocabulary", "単語"],["grammar", "文法"], ["speaking", "スピーキング"], ["writing", "ライティング"], ["listening", "リスニング"],["reading","リーディング"]]%></div>
        <div class="study-content"><%= f.select :study_time, [["study hours",nil],["１０分", 3000],["２０分", 20],["３０分", 30],["４０分", 40],["５０分", 50],["６０分", 60],["７０分", 70],["８０分", 80],["９０分", 90],["１００分", 100],["１２０分", 120],["１３０分", 130],["１４０分", 140],["１５０分", 150]] %></div>
      </div>
      <div><%= f.text_area :writing,class: 'form-message2', placeholder: 'diary' %></div>
  </div>
  <%= f.submit '送信', class: 'form-submit2' %>
<% end %>

app/views/diaries/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= @diary.user.name %>
    </div>
    <div class="message-date">
      <%=@diary.created_at.strftime('%m/%d %H:%M') if @diary%>
    </div>
    <div class="message-date">

    </div>
    <div>
    <% if current_user.genre == "教員" %>
      <p>
        <%= button_to room_message_path(@room.id, message.id) ,method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
      <% elsif user_signed_in? && current_user.id == message.user_id %>
      <p>
        <%= button_to room_message_path(@user.id, @diary.id), method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
    <% end %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%=link_to @diary.writing, new_message_comment_path(@diary) %>
    </div>
     <%= link_to  new_message_comment_path(@diary) do %>
     <%end%>
  </div>
</div>

app/views/diaries/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name2">
  <%=@user.name%>
  <%= render "layouts/level" %>
  <div><%=@user.current_sign_in_at.strftime('%m/%d %H:%M') if @user.current_sign_in_at%></div>
  </div>
  <div>
  <%if @user.diaries.present?%>
  <div class="diary-study-time"><%=link_to "data", diary_path(@user.diary_ids) %></div>
  <div class="back-from-diary"><%=link_to "back", root_path %></div>
  <%else%>
  <div class="back-from-diary2"><%=link_to "back", root_path %></div>
  <%end %>
  </div>
</div>

<div class="rooms">
  <% @diaries.each do |diary| %>
    <div class="room2">
      <div class="room-name">
      <%=link_to new_diary_reply_path(diary) do %>
         <div class="diary-title2"><%=diary.title %></div>
         <div><%=diary.created_at.strftime('%m/%d %H:%M') if diary %></div>
         <% end %>
      </div>
    </div>
    <%end%>
  <div class="room-members">  

  </div>
</div>

app/views/diaries/new.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main" %>
  </div>
</div>

app/views/diaries/show.html.erb
<div class="page-title"><%=link_to @user.name, new_user_diary_path(@user)%>さんのデータ</div>
<div class="study-data">
<div class="content-bar-chart">
<div class="study-hour-wrapper">
<div class="study-wrapper voca">
<div class="studies">Vocabulary</div>
<%@array_word = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "単語"%>
    <%@sum_word = diary.study_time%>
    <%@array_word << @sum_word%>
<%else%>
    <%@sum_word = 0%>
    <%@array_word << @sum_word%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_word.sum%></b><span class="mins">mins</span></div>
</div>


<div class="study-wrapper gra">
<div class="studies">Grammar</div>
<%@array_grammar = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "文法"%>
    <%@sum_grammar = diary.study_time%>
    <%@array_grammar << @sum_grammar%>
<%else%>
    <%@sum_grammar = 0%>
    <%@array_grammar << @sum_grammar%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_grammar.sum%></b><span class="mins">mins</span></div>
</div>


<div class="study-wrapper spe">
<div class="studies">Speaking</div>
<%@array_speaking = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "スピーキング"%>
    <%@sum_speaking = diary.study_time%>
    <%@array_speaking << @sum_speaking%>
<%else%>
    <%@sum_speaking = 0%>
    <%@array_speaking << @sum_speaking%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_speaking.sum%></b><span class="mins">mins</span></div>
</div>

<div class="study-wrapper wri">
<div class="studies">Writing</div>
<%@array_writing = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "ライティング"%>
    <%@sum_writing = diary.study_time%>
    <%@array_writing << @sum_writing%>
<%else%>
    <%@sum_writing = 0%>
    <%@array_writing << @sum_writing%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_writing.sum%></b><span class="mins">mins</span></div>
</div>



<div class="study-wrapper lis">
<div class="studies">Listening</div>
<%@array_listening = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リスニング"%>
    <%@sum_listening = diary.study_time%>
    <%@array_listening << @sum_listening%>
<%else%>
    <%@sum_listening = 0%>
    <%@array_listening << @sum_listening%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_listening.sum%></b><span class="mins">mins</span></div>
</div>

<div class="study-wrapper rea">
<div class="studies">Reading</div>
<%@array_reading = []%>
<%@diaries.each do |diary|%>
<%if diary.study_content == "リーディング"%>
    <%@sum_reading = diary.study_time%>
    <%@array_reading << @sum_reading%>
<%else%>
    <%@sum_reading = 0%>
    <%@array_reading << @sum_reading%>
<%end%>
<%end%>

<div class="study-hour"><b><%=@array_reading.sum%></b><span class="mins">mins</span></div>
</div>

<div class="study-wrapper total-hours">
<div class="studies"><span>total</span></div>
<div class="study-hour"><b><%=@array_word.sum + @array_reading.sum + @array_speaking.sum + @array_grammar.sum + @array_listening.sum + @array_writing.sum%></b><span class="mins">mins</span></div>
</div>

</div>
    <div class="bar-chart">
        <%= column_chart @bar_chart.group(:study_content).sum(:study_time),id: "column-chart", width: "700px", height: "450px",ytitle: "mins",colors: ['#CCCCCC']%>
    </div>
</div>

<div class="contents">
    <div class="content">
        <div class="content-title vocabulary">Vocabulary</div>
        <%= line_chart @vocabulary.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['rgb(28, 88, 255)'] %>
    </div>

    <div class="content">
        <div class="content-title grammar">Grammar</div>
        <%= line_chart @grammar.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['rgb(255, 213, 0)'] %>
    </div>

    <div class="content">
        <div class="content-title speaking">Speaking</div>
        <%= line_chart @speaking.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['#8074d1'] %>
    </div>

    <div class="content">
       <div class="content-title writing">Writing</div>
       <%= line_chart @writing.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['#a94141'] %>
    </div>

    <div class="content">
       <div class="content-title listening">Listening</div>
       <%= line_chart @listening.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['#FFBBFF'] %>
    </div>

    <div class="content">
       <div class="content-title reading">Reading</div>
       <%= line_chart @reading.group_by_day(:created_at).sum(:study_time), width: "600px", height: "150px",ytitle: "mins",colors: ['#008080'] %>
    </div>

</div>
</div>