config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  delete "messages/:id" => "messages#destroy"
  get 'comments/index'
  delete 'messages' => 'messages#destroy'
  delete 'responses' => 'responses#destroy'
  get 'responses/create' => 'responses#create'
  get 'agrees' => 'agrees#show'
  get 'explanations' => 'explanations#index'
  get 'tips/lists' => 'tips#lists'
  get 'tips/questions' => 'tips#questions'
  get 'tips/hours' => 'tips#hours'
  get 'tips/levels' => 'tips#levels'
  get 'tips/commentnum' => 'tips#commentnum'
  get 'rooms/students' => 'rooms#students'
  get 'messages/students' => 'messages#students'
  get 'messages/list' => 'messages#list'
  get 'messages/levelup' => 'messages#levelup'
  get 'diaries/count_words' => 'diaries#count_words'
  get '/users/sign_out' => 'devise/sessions#destroy'

  root to: "rooms#index"
  resources :users, only: [:edit, :update] do
    resources :diaries, only: [:index, :new, :create,:destroy, :show]  end

  resources :rooms do
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :tasks
  end

  resources :messages, only: [:index, :new, :create, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  resources :comments do
    resources :agrees, only: [:create, :destroy]
  end

  resources :comments do
    resources :responses, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :tips
  end

  resources :diaries do
    resources :replies, only: [:new, :create, :destroy]
  end

  resources :users do
    resources :exams, only: [:new, :create, :destroy, :show]
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_users
    has_many :users, through: :room_users, dependent: :destroy
    has_many :messages, dependent: :destroy
    has_many :tasks, dependent: :destroy
    validates :name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
    end

    def new
        @room = Room.new
    end

    def show
        @room = Room.find(params[:id])
        @users = @room.users.order("student_number ASC")
    end

    def create
        @room = Room.new(room_params)
        if @room.save
            redirect_to root_path
        else
            render :new
        end
    end

    def destroy
        room = Room.find(params[:id])
        room.destroy
        redirect_to root_path
    end

    private

    def room_params
        params.require(:room).permit(:name, user_ids: [])
    end
end

app/views/rooms/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <%=  l message.created_at %>
    </div>
    <div class="message-date">
      【質問<%= message.comments.count %>個】
    </div>
    <div>
    <% if current_user.genre == "教員" %>
      <p>
        <%= button_to room_message_path(@room.id, message.id) ,method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
      <% elsif user_signed_in? && current_user.id == message.user_id %>
      <p>
        <%= button_to room_message_path(@room.id, message.id), method: :delete, class: "delete-button" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </p>
    <% end %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%=link_to message.content, new_message_comment_path(message) %>
    </div>
     <%= link_to  new_message_comment_path(message) do %>
     <%=image_tag message.image.variant(resize: '400x400'), class: 'message-image' if message.image.attached? %>
     <%end%>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar2" %>
  </div>
  <div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%=link_to "生徒一覧",messages_list_path, class:"qs1" %>
      <%=link_to "クイズ",tips_questions_path, class:"qs3" %>
      <%# <%=link_to "勉強時間",tips_hours_path, class:"qs4" %>
      <%=link_to "考査",new_user_exam_path(current_user), class:"qs5" %>
      <%# <%=link_to "レベル",messages_levelup_path, class:"qs3" %>


    </div>
  </div>
  <div class="right-header">

  </div>
</div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1 class="new-chat-room">新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <%= hidden_field_tag :id,@room.id %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
   
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      <% @num= "student_number ASC"%>
              <div class="class-num1">１−１</div><%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:1).all.order(@num), :id, :name %>
              <div class="class-num1">１−２</div><%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:2).all.order(@num), :id, :name %>
              <div class="class-num1">１−３</div><%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:3).all.order(@num), :id, :name %>
              <div class="class-num1">１−４</div> <%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:4).all.order(@num), :id, :name %>
              <div class="class-num1">１−５</div> <%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:5).all.order(@num), :id, :name %>
              <div class="class-num1">１−６</div> <%= f.collection_check_boxes :user_ids, User.where(grade:1, class_number:6).all.order(@num), :id, :name %>
              <div class="class-num2">２−１</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:1).all.order(@num), :id, :name %>
              <div class="class-num2">２−２</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:2).all.order(@num), :id, :name %>
              <div class="class-num2">２−３</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:3).all.order(@num), :id, :name %>
              <div class="class-num2">２−４</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:4).all.order(@num), :id, :name %>
              <div class="class-num2">２−５</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:5).all.order(@num), :id, :name %>
              <div class="class-num2">２−６</div> <%= f.collection_check_boxes :user_ids, User.where(grade:2, class_number:6).all.order(@num), :id, :name %>
              <div class="class-num3">３−１</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:1).all.order(@num), :id, :name %>
              <div class="class-num3">３−２</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:2).all.order(@num), :id, :name %>
              <div class="class-num3">３−３</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:3).all.order(@num), :id, :name %>
              <div class="class-num3">３−４</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:4).all.order(@num), :id, :name %>
              <div class="class-num3">３−５</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:5).all.order(@num), :id, :name %>
              <div class="class-num3">３−６</div> <%= f.collection_check_boxes :user_ids, User.where(grade:3, class_number:6).all.order(@num), :id, :name %>
          </div>

        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="room-name2">
<%=link_to @room.name, room_messages_path(@room), class:"room-name3"%>
</div>
<%@users.each do |user| %>
<%if user.genre == "生徒"%>
<div class="students-in-room">
    <div class="stu-num"><%=user.student_number%>番</div>　　
    <% @d_path = link_to user.name,new_user_diary_path(user)%>
    <%if user.name.length == 1%>
    <div class="stu-name0"><%=@d_path%></div>　　
    <%elsif user.name.length == 2%>
    <div class="stu-name"><%=@d_path%></div>　　
    <%elsif user.name.length == 3%>
    <div class="stu-name1"><%=@d_path%></div>　　
    <% elsif user.name.length == 4%>
    <div class="stu-name2"><%=@d_path%></div>　　　
    <% elsif user.name.length == 5%>
    <div class="stu-name3"><%=@d_path%></div>　　　
    <% elsif user.name.length == 6%>
    <div class="stu-name4"><%=@d_path%></div>　　　
   <% end %>
    <div><%=user.current_sign_in_at.strftime('%m/%d %H:%M') %></div>
    <% @login = user.current_sign_in_at if user.current_sign_in_at%>
    <%if @login < Date.current.ago(5.days || 6.days || 7.days)%>
    <div class="login-day">　　５日間以上未ログイン</div>
    <%elsif @login < Date.current.ago(4.days)%>
    <div class="login-day">　　５日前にログインしました</div>
    <%elsif @login < Date.current.ago(3.days)%>
    <div class="login-day">　　４日前にログインしました</div>
    <%elsif @login < Date.current.ago(2.days)%>
    <div class="login-day">　　３日前にログインしました</div>
    <%elsif @login < Date.current.ago(1.day)%>
    <div class="login-day">　　２日前にログインしました</div>
    <% end %>
</div>
<% end %>
<% end %>